#!/bin/bash
gcc -Wall -Wextra -Werror -pedantic  -std=gnu89 107-main.c 107-quick_sort_hoare.c print_array.c -o quick
gcc -Wall -Wextra -Werror -pedantic  -std=gnu89 107-main2.c 107-quick_sort_hoare.c print_array.c -o quick2
